### ISSUE TITLE
Ability to change my display name

### ISSUE THREAD

**Issue by ap--** [laminlabs/laminhub-public#4]
Hello Lamin Team,

I signed up on lamin.ai using my github account, and it seems I can't change my display name in the laminhub.

I expected to be able to change it in the settings menu.

Cheers,
Andreas 😃

**Comment by falexwolf** [comment]
Yes, absolutely right. We just got additional help on the team and we'll start to fill in these small things. We had this in our old UI but haven't gotten around to add it to the new UI.
