### ISSUE TITLE
500 error on lamin.ai/dashboard

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/laminhub-public#7]
### Report

More details to come.

**Comment by chris-soelistyo** [comment]
Hi, 

I'm getting the same issue; account name is `cs60`

Attached is a screenshot of the network tab.
![Screenshot 2024-09-20 at 18 54 35](https://github.com/user-attachments/assets/617a5af3-f676-49c7-9bb0-ce4a11b8c1dc)

**Comment by falexwolf** [comment]
Hi guys! Sorry about this.

Let us know in case the issue persists. @chaichontat deployed what could be a fix to prod. It seems an edge case with particular google accounts (we can reproduce it only with some google accounts).
